name: instagram
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  
  # Navigator 2.0
  beamer: 

  # Firebase
  flutterfire_ui:
  flutter_facebook_auth:
  google_sign_in:
  firebase_core:
  firebase_auth:

  # Bloc
  bloc: 
  flutter_bloc:
  hydrated_bloc:

  # System
  path_provider:
  logger:
  image_picker:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  bloc_test:
  mocktail:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
