name: Flutter Build and Deploy to Play Store
on: 
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Appbundle
    runs-on: macos-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Setting Up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setting up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Decoding Upload-keystore.jks file
        run: echo "${{secrets.UPLOAD_KEYSTORE_FILE}}" | base64 --decode > ./android/upload-keystore.jks

      - name: Decoding key.properties file
        run: echo "${{secrets.KEY_PROPERTIES}}" | base64 --decode > ./android/key.properties

      - name: Decoding Firebase_options.dart
        run: echo "${{secrets.FIREBASE_OPTIONS_DART}}" | base64 --decode > ./lib/firebase_options.dart

      - name: Build Flutter release for android
        run: flutter clean ; flutter pub get; flutter build appbundle

      - name: create Service Account json file
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > service_account.json

      - name: Publish to PlayStore for Open Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: dev.dishank.instagram
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: beta
          status: completed
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          whatsNewDirectory: distribution/whatsnew
